use_frameworks!

target 'OFArchiver_Example' do
  pod 'OFArchiver', :path => '../'

  target 'OFArchiver_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
