source 'git@101.200.84.148:ios-ofashionspecs/com-ofashion-specs.git'
source 'git@101.200.84.148:ios-ofashionspecs/com-ofashion-specs_mirror.git'


target 'OFArchiver_Example' do
  pod 'OFArchiver', :path => '../'

  target 'OFArchiver_Tests' do
    inherit! :search_paths

  end
end
